### ISSUE TITLE
2015/03/07 01:19:08 rfc5424: write udp 54.236.80.3:514: message too long

### ISSUE THREAD

**Issue by MrJoy** [gliderlabs/logspout#55] opened 2015-03-07 01:32 UTC
When this occurs, Logspout crashes.  Minimally, this should be handled a bit more gracefully so that a badly behaved app can't interfere with log capture.

That said, it looks like the Deis folks have a patch:

https://github.com/deis/deis/pull/2375/files

**Comment by progrium** [comment] 2015-03-07 15:19
Cool, it's fixed in new branch that'll be in master soon.

**Closed** 2015-03-24 01:44 UTC

**Comment by nagliyvred** [comment] 2015-04-08 00:38
hi Jeff, 
Is this in master at the moment? If not, can you refer me to the branch you're talking about?
Also, what's the root cause of that? Is it the log message being too long to be handled by logspout or by downstream syslog service? What should I do with this if I have potentially longer log messages (with stack traces and so on)?

Thanks

**Comment by gigablah** [comment] 2015-04-09 00:19
Yeah logspout is really unreliable for me now. Seems like any error will cause logspout to just stop working until you restart it, whether it's "message too long" for UDP or "connection timed out" for TCP.

**Comment by progrium** [comment] 2015-04-09 00:24
@gigablah you should file issues for specific behavioral changes that you want to see. I think it's only half fair to say it's "unreliable" ... it's failing fast on errors. Either give it a restart policy or get specific about what it should do instead. :)

**Comment by gigablah** [comment] 2015-04-09 00:31
A restart policy sounds good but the thing is that the logspout process continues running so it wouldn't trigger. Is there some sort of "exit upon error" flag?

**Comment by progrium** [comment] 2015-04-09 00:34
Oh I thought it did. It doesn't. That's right. Yes, an "exit on error" behavior option is probably called for. In fact, if there is only one adapter, it should always do that.

**Comment by gigablah** [comment] 2015-04-09 00:35
Great :) Maybe I should file this as a separate issue? Or maybe you can do that.

**Comment by progrium** [comment] 2015-04-09 00:36
I edited my comment to suggest that, yes please.
