### ISSUE TITLE
Logspout stops logging after truncating a logfile from a container

### ISSUE THREAD

**Issue by SqiSch** [gliderlabs/logspout#216] opened 2016-07-28 15:53 UTC
Logspout stops logging after truncating a logfile from a container

to reproduce this, follow these steps: 

start a container f.e.:
`docker run -d ubuntu /bin/sh -c "while true; do echo hello world; sleep 1; done"`

check the logging via logspout: 
`curl localhost:7477/logs`

then truncate the logfile from the hello world container:
`truncate -s0 /data/docker/containers/zzzzz/yyyyyyy-json.log`

check the logging via logspout again: 
`curl localhost:7477/logs`

To fix the logging we need to restart logspout OR the hello world container, but the hello world container stills logging into the logfile.json

**Comment by furkanayhan** [comment] 2016-08-11 08:32
any update on this issue? @SqiSch

**Comment by sybrandy** [comment] 2016-08-12 13:19
I saw something similar today where I started logspout after some other containers and didn't get any logs.  I restarted the one container and logs started to come through.

**Comment by furkanayhan** [comment] 2016-08-12 13:22
For those who are dealing with this issue:
We are trying this tool now: https://sematext.com/blog/2016/04/04/docker-cloud-monitoring-logging/
And it seems to be working.

**Comment by ebr** [comment] 2016-08-28 16:54
we started running into this recently, and i suspect there was a change in how the docker daemon rotates the logs in v1.12, though I cannot find anything to support this in the v1.12 release notes. this is a big deal because we can't turn off log rotation.

**Comment by ebr** [comment] 2016-08-28 16:59
this may be the reason:
https://github.com/docker/docker/issues/23913

and this might be the fix:
https://github.com/docker/docker/pull/24514

**Comment by ebr** [comment] 2016-09-08 18:05
FWIW, we switched to `journald` log driver in docker (from `json-file`), and this is no longer an issue, because there's no file to be truncated. If you are stuck using `json-file` driver, this is definitely an issue. I actually had to create a "helper" service that would restart all logspout containers hourly as a workaround (and of course there was still a potential of missing up to 1 hour of logs, in case the truncation happened right after a restart)

**Comment by mfornasa** [comment] 2016-10-06 08:52
Any update here? We are experiencing this issue on Docker Cloud. Any workaround?

**Comment by sybrandy** [comment] 2016-10-06 12:01
The suggestion by @ebr to use journald appears to be working for me in some testing I was doing.  If you can do that, I'd try that first.

**Comment by mfornasa** [comment] 2016-10-06 12:03
@sybrandy my problem is that I am on Docker Cloud. They don't support docker log drivers.

**Comment by olivergrahl** [comment] 2016-11-18 09:09
I'm on Docker Cloud as well, experiencing the problem of logspout stopping to log from some containers after hours, from other containers after days, frequently. After trying many other possible logspout fixes (#235, #210) I found this issue and can confirm that Docker Cloud's log rotation was the culprit. By default, Docker Cloud rotates logs at 10M file size, and Logspout will stop working immediately after a log gets rotated.
I fixed this by monitoring the log directory and restarting Logspout when logs get rotated. With my current solution, [logspout-restart](https://hub.docker.com/r/ograhl/logspout-restart/), I may miss some logs for 10-20 seconds, but besides that, logging has finally been fixed for me.

**Comment by fslDev** [comment] 2016-12-12 17:01
@olivergrahl  It looks like gliderlabs pulled a workaround for this issue into the `master` branch back in November:

https://github.com/gliderlabs/logspout/commit/977986a9e30db2fb37ba6401f1c1ab4082de40d5

The patch was not pulled into `latest`.  I just changed my docker service to pull from `master` so I guess I'll see if it works.

**Comment by freekrai** [comment] 2016-12-13 16:22
Testing on our docker cloud now.

**Comment by patagona-afriemann** [comment] 2016-12-14 14:33
We might be running into the same issue with logspout on kubernetes. Logspout stops sending messages after some time. I built a custom container from the master branch and [977986a](https://github.com/gliderlabs/logspout/commit/977986a9e30db2fb37ba6401f1c1ab4082de40d5) is included.

**Comment by yunspace** [comment] 2017-01-09 00:43
I believe this issue may also be effecting Rancher also. I've been seeing logging stop periodically and requires a restart of logspout. Will try out the work around in 977986a

**Comment by mhassankhan** [comment] 2017-01-12 07:13
We're experiencing the same issue on docker cloud. Have been using the solution proposed/designed by @olivergrahl (thanks!). Can anyone confirm whether the master branch solves it and doesn't introduce any new issues?

**Comment by patagona-afriemann** [comment] 2017-01-12 10:31
Our workaround was to use the journald logdriver as suggested earlier, so no clue as to the current behavior.

**Comment by SqiSch** [comment] 2017-01-12 10:40
Our Workaround is to restart the logspout container after truncating the logfiles.

**Comment by daniilyar** [comment] 2017-01-12 22:02
Affects us also. We use Kubernetes, which by default installs logrotate rule truncating docker container JSON logs from time to time. Anytime log for container is truncated, logspout stops sending logs for this container.

**Comment by sybrandy** [comment] 2017-01-13 12:54
@daniilyar Have you tried switching to journald for docker logs?  That's been working for us, though we are not using Kubernetes.

**Comment by daniilyar** [comment] 2017-01-16 20:17
@sybrandy, we don't want to switch to journald as we want docker logs feature to work at our environments

**Comment by mattaitchison** [comment] 2017-01-16 20:26
Docker v1.13.x includes docker/docker#24514 which should fix this issue. @daniilyar Are you able to test it?

**Comment by daniilyar** [comment] 2017-01-16 21:52
@mattaitchison, thank you! 1.13 is still pre-release version, but I am going to try it out our DEV environment this week.

**Comment by sybrandy** [comment] 2017-01-17 16:50
@daniilyar What do you mean by "we want docker logs feature to work at our environments"?  We're using journald in our staging environment and "docker logs" is working fine.

**Comment by patagona-afriemann** [comment] 2017-01-17 18:17
@sybrandy I'd say it's a reasonable request. Journald is systemd specific and luckily some distributions still use other init systems.

**Comment by sybrandy** [comment] 2017-01-17 18:26
@patagona-afriemann Ugh, yeah, I forgot about that.  I'm stuck in the CentOS/Systemd world, so that never even crossed my mind.  My bad.

**Comment by rocketraman** [comment] 2017-02-27 20:00
I'm having an issue where logspout simply stops capturing logs until a restart, and I'm wondering if the cause is this issue. I am on Docker 1.13.1, and using recent commit 6c88eec, so my problem at least is clearly not solved by Docker 1.13 and https://github.com/docker/docker/pull/24514.

I can't use journald either (Docker on Azure), though I'd love to.

**Comment by rocketraman** [comment] 2017-02-27 21:04
> I'm having an issue where logspout simply stops capturing logs until a restart

Actually, ignore this, it appears the problem was elsewhere.

**Comment by jmreicha** [comment] 2017-03-26 02:55
Seeing this as well.  Can anybody confirm if this issue is fixed by upgrading to Docker 1.14?

**Comment by jacohend** [comment] 2017-03-29 20:00
Also seeing this. Running 1.13.1 and still seeing logspout stop logging after auto-jsonfile truncation

**Comment by gaieges** [comment] 2017-03-29 20:39
I was chatting with @progrium the other day, and the main issue why these bugs remain open is that there's a lack of capacity to maintain this project.  It seems as though they'd love to accept help from those who are willing and have some available cycles.

Anyone interested?

**Comment by michaelshobbs** [comment] 2017-03-29 20:52
I'm currently working on expanding the test suite so we can more reliably accept PRs. #276 is a start

**Comment by michaelshobbs** [comment] 2017-03-30 21:47
Are folks still seeing this exact issue using docker 1.13.x and logspout master? I'm looking to cut a build soon and curious if perhaps the fix is already done in master.

**Comment by freekrai** [comment] 2017-03-30 21:48
Still seeing it

**Comment by michaelshobbs** [comment] 2017-03-30 21:49
@freekrai are you using docker 1.13.x and logspout:master or logspout:latest?

**Comment by freekrai** [comment] 2017-03-30 21:52
This is docker 1.13.x and we've tried both master and latest.

It seemed fine at first but it wasn't long before we were back in the same place we were before

**Comment by imjosh** [comment] 2017-03-30 22:19
I believe the problem is solved in logspout:master but you have to set an envvar like `INACTIVITY_TIMEOUT = 5m` for it to work.  

I was having this problem before and it cleared up after I switched to master and set that variable.  I'm using Docker 1.11.1-cs1

**Comment by michaelshobbs** [comment] 2017-03-30 22:41
@freekrai can you try @imjosh's suggestion and report back?

**Comment by rocketraman** [comment] 2017-03-30 23:13
> I believe the problem is solved in logspout:master but you have to set an envvar like INACTIVITY_TIMEOUT = 5m for it to work.

If I understand `INACTIVITY_TIMEOUT` correctly, this just means that logspout will miss 5 minutes of logs after a rotation, and then start logging again.

**Comment by michaelshobbs** [comment] 2017-03-30 23:29
I believe in the current state, logspout will send the backlog.

**Comment by idyll** [comment] 2017-03-31 14:16
I am testing the fix on several stacks right now and will report back my results.

**Comment by freekrai** [comment] 2017-04-07 17:08
Can confirm that with that fix... still seeing logs freeze.

**Comment by mattaitchison** [comment] 2017-04-08 01:01
Is anyone able to check if they have `--log-opt max-file=2` set on the daemon?

https://github.com/docker/docker/issues/32038#issuecomment-288730458

**Comment by jmreicha** [comment] 2017-04-14 18:21
Has anybody been able to confirm adding `INACTIVITY_TIMEOUT = 5m` gets logs flowing again?

**Comment by say5** [comment] 2017-04-19 07:37
Docker 1.12.6, `--log-opt max-file=2`, master, INACTIVITY_TIMEOUT, still seeing freezes. In logspout logs I see: `stopped with error: inactivity time exceeded timeout` for the same container over and over again.

**Comment by michaelshobbs** [comment] 2017-04-19 14:58
@say5 what version of logspout did you test?

**Comment by say5** [comment] 2017-04-19 16:42
@micahhausler `:master`

**Comment by michaelshobbs** [comment] 2017-04-19 18:32
@say5 `:master` when though? what is in `/src/VERSION` 

example:
```
$ docker run -ti --rm --entrypoint="/bin/sh" gliderlabs/logspout:master
/ # cat /src/VERSION
v3.3-dev
```

**Comment by jarrold** [comment] 2017-04-19 23:22
I'm on `Docker Version 1.11.2-cs5` and `INACTIVITY_TIMEOUT=1m` and its not flowing after `dockercloud/logrotate:latest` truncates the log every 5mins 

```
[logspout-production-1]2017-04-19T23:04:31.837226222Z # logspout v3.3-dev-custom by gliderlabs
[logspout-production-1]2017-04-19T23:04:31.837251855Z # adapters: udp logstash raw tcp
[logspout-production-1]2017-04-19T23:04:31.837258270Z # options : debug:true persist:/mnt/routes
[logspout-production-1]2017-04-19T23:04:31.837505225Z 2017/04/19 23:04:31 setting allowTTY to: false
[logspout-production-1]2017-04-19T23:04:32.146998753Z # jobs    : http[]:80 pump routes
[logspout-production-1]2017-04-19T23:04:32.147042355Z # routes  :
[logspout-production-1]2017-04-19T23:04:32.147047588Z #   ADAPTER	ADDRESS	CONTAINERS	SOURCES	OPTIONS
[logspout-production-1]2017-04-19T23:04:32.147055154Z #   logstash+tcplogstash:5000	map[]
[logspout-production-1]2017-04-19T23:04:32.147143319Z 2017/04/19 23:04:32 pump.Run(): using inactivity timeout:  1m0s
```

I'm seeing this in the logs

```
[logspout-production-1]2017-04-19T23:14:31.495767350Z 2017/04/19 23:14:31 pump.send(): send timeout, closing
[logspout-production-1]2017-04-19T23:14:31.511068749Z 2017/04/19 23:14:31 pump.send(): send timeout, closing
[logspout-production-1]2017-04-19T23:14:31.558842272Z 2017/04/19 23:14:31 pump.send(): send timeout, closing
[logspout-production-1]2017-04-19T23:14:31.559377513Z 2017/04/19 23:14:31 pump.send(): send timeout, closing
[logspout-production-1]2017-04-19T23:14:31.570345259Z 2017/04/19 23:14:31 pump.send(): send timeout, closing
```

**Comment by jarrold** [comment] 2017-04-20 10:00
@michaelshobbs I think that fixed it. My logs have been flowing for the last few hours. Thanks for this. I didn't use your image ID but I did build a fresh custom image from master.

**Comment by michaelshobbs** [comment] 2017-04-20 15:38
Awesome! closing.

**Closed by michaelshobbs** 2017-04-20 15:38 UTC
Labels: status: needs more info, type: bug

**Comment by matgenois** [comment] 2017-06-01 18:49
I still have this issue. I have installed logspout may 29th so I'm suppose to have the fix. After the logrotate occurs, I must restart logspout so I can have my log in logdna.com

**Comment by josegonzalez** [comment] 2017-06-01 20:06
@matgenois how did you install logspout?

**Comment by matgenois** [comment] 2017-06-02 12:40
I used this command provided to me by logdna.com :  
`sudo docker run --name="logdna" --restart=always -d -v=/var/run/docker.sock:/var/run/docker.sock -e SYSLOG_STRUCTURED_DATA="logdna@48950 tag=\"docker\"" gliderlabs/logspout syslog+tls://syslog-a.logdna.com:37555`

**Comment by michaelshobbs** [comment] 2017-06-07 16:02
related #309
