### ISSUE TITLE
Can't run logspout

### ISSUE THREAD

**Issue by jnardiello** [gliderlabs/logspout#190] opened 2016-05-18 17:14 UTC
// Reposting as previously I used the wrong account

I'm simply trying to get started with logspout. I don't want to do anything fancy, just start it and consume the logs with curl.
Doesn't matter how I try to run it, I keep getting:

```
# logspout v3 by gliderlabs
# adapters: raw tls udp tcp syslog
# options : persist:/mnt/routes
# jobs    : http[logs,routes]:80 pump
# routes  : none
2016/05/18 17:04:39  ended: %!s(<nil>)
```

I've seen a number of other issues related to this and someone is suggesting to start it passing routes as a parameter. Unfortunately I wasn't able to understand how to do it.

Anyone that could help?

**Comment by mattaitchison** [comment] 2016-05-23 21:41
duplicate of #185

**Closed by mattaitchison** 2016-05-23 21:41 UTC
