### ISSUE TITLE
TCP Loggly example

### ISSUE THREAD

**Issue by sigismond-medullan** [gliderlabs/logspout#25] opened 2014-10-16 01:46 UTC
I am wondering if it is possible to take the log output and forward it over tcp and if so could you provide an example? I am trying do an integration with Loggly.

**Comment by mgood** [comment] 2015-02-10 21:15
This looks like a duplicate of issue #1 which discusses adding TCP support.

**Comment by harlow** [comment] 2015-03-08 17:23
Here is the format for sending to Loggly:

```
sudo docker run --restart=always -d -v=/var/run/docker.sock:/tmp/docker.sock \
  progrium/logspout rfc5424://logs-01.loggly.com:514?structuredData=[LOGGLY_TOKEN]@41058
```

https://www.loggly.com/docs/streaming-syslog-without-using-files/

**Comment by progrium** [comment] 2015-03-24 01:48
With master you should now be able to send to loggly over TCP as well as UDP:

syslog+tcp://logs-01.loggly.com:514?structured_data=[LOGGLY_TOKEN]@41058

**Closed by progrium** 2015-03-24 01:48 UTC

**Comment by nagliyvred** [comment] 2015-04-03 04:25
Can't get it working :( 
That's what I get on master: 
```
[logspout2-3] 2015-04-03T04:10:49.341040520Z # logspout v3-master by gliderlabs
[logspout2-3] 2015-04-03T04:10:49.341268458Z # adapters: udp tcp syslog raw
[logspout2-3] 2015-04-03T04:10:49.341302647Z # options : persist:/mnt/routes
[logspout2-3] 2015-04-03T04:10:49.341822957Z panic: runtime error: assignment to entry in nil map
[logspout2-3] 2015-04-03T04:10:49.341822957Z 
[logspout2-3] 2015-04-03T04:10:49.341822957Z goroutine 16 [running]:
[logspout2-3] 2015-04-03T04:10:49.341822957Z runtime.panic(0x7af000, 0xa1d5d3)
[logspout2-3] 2015-04-03T04:10:49.341822957Z 	/usr/lib/go/src/pkg/runtime/panic.c:279 +0xf5
[logspout2-3] 2015-04-03T04:10:49.341822957Z github.com/gliderlabs/logspout/router.(*RouteManager).AddFromUri(0xc208024de0, 0x7fff701c9d34, 0x5e, 0x0, 0x0)
[logspout2-3] 2015-04-03T04:10:49.341822957Z 	/go/src/github.com/gliderlabs/logspout/router/routes.go:102 +0x4b3
[logspout2-3] 2015-04-03T04:10:49.341822957Z github.com/gliderlabs/logspout/router.(*RouteManager).Setup(0xc208024de0, 0x0, 0x0)
[logspout2-3] 2015-04-03T04:10:49.341822957Z 	/go/src/github.com/gliderlabs/logspout/router/routes.go:184 +0x1bb
[logspout2-3] 2015-04-03T04:10:49.341822957Z main.main()
[logspout2-3] 2015-04-03T04:10:49.341822957Z 	/go/src/github.com/gliderlabs/logspout/logspout.go:39 +0x646
[logspout2-3] 2015-04-03T04:10:49.341822957Z 
[logspout2-3] 2015-04-03T04:10:49.341822957Z goroutine 17 [runnable]:
[logspout2-3] 2015-04-03T04:10:49.341822957Z runtime.MHeap_Scavenger()
[logspout2-3] 2015-04-03T04:10:49.341822957Z 	/usr/lib/go/src/pkg/runtime/mheap.c:507
[logspout2-3] 2015-04-03T04:10:49.341822957Z runtime.goexit()
[logspout2-3] 2015-04-03T04:10:49.341822957Z 	/usr/lib/go/src/pkg/runtime/proc.c:1445
[logspout2-3] 2015-04-03T04:10:49.341822957Z 
[logspout2-3] 2015-04-03T04:10:49.341822957Z goroutine 18 [runnable]:
[logspout2-3] 2015-04-03T04:10:49.341822957Z bgsweep()
[logspout2-3] 2015-04-03T04:10:49.341822957Z 	/usr/lib/go/src/pkg/runtime/mgc0.c:1976
[logspout2-3] 2015-04-03T04:10:49.341822957Z runtime.goexit()
[logspout2-3] 2015-04-03T04:10:49.341822957Z 	/usr/lib/go/src/pkg/runtime/proc.c:1445
[logspout2-3] 2015-04-03T04:10:49.341822957Z 
[logspout2-3] 2015-04-03T04:10:49.341822957Z goroutine 19 [runnable]:
[logspout2-3] 2015-04-03T04:10:49.341822957Z runfinq()
[logspout2-3] 2015-04-03T04:10:49.341822957Z 	/usr/lib/go/src/pkg/runtime/mgc0.c:2606
[logspout2-3] 2015-04-03T04:10:49.341822957Z runtime.goexit()
[logspout2-3] 2015-04-03T04:10:49.341822957Z 	/usr/lib/go/src/pkg/runtime/proc.c:1445
```
Using url like this `syslog+tcp://logs-01.loggly.com:514?structured_data=<token>@41058`

on `latest` I get (using either syslog+tcp or rfc5424 as a protocol):
```
[logspout2-3] 2015-04-03T04:16:19.158154798Z 2015/04/03 04:16:19 routing all to rfc5424://logs-01.loggly.com:514?structured_data=<token>@41058
[logspout2-3] 2015-04-03T04:16:19.158192245Z 2015/04/03 04:16:19 loading and persisting routes in /mnt/routes
[logspout2-3] 2015-04-03T04:16:19.158327859Z 2015/04/03 04:16:19 logspout v2 serving http on :8000
```
But no data ends up in loggly...
Also, last two posts confused me as to whether I should be adding `structured_data=xxx` or `structuredData=xxx` to the url?

**Comment by mbabineau** [comment] 2015-04-03 21:47
I'm seeing the same issue with the `v2` release. I kicked off a task to generate logs and tried each combination of `structured_data`/`structuredData` and `rfc5424`/`syslog+tcp`. Nothing ever showed up in Loggly. 

Note that for `syslog+tcp`, the HTTP endpoint did not return any of the generated logs, either.

#### rfc5424
##### structured_data
```console
root@ip-10-0-1-175:~# docker run -d -P -v=/var/run/docker.sock:/tmp/docker.sock gliderlabs/logspout:v2 "rfc5424://logs-01.loggly.com:514?structured_data=<token>@41058"
a3c3c3afa6701b8090425a474cf5572cc9bb2e68e91b8dcb54038ba74938baa0

root@ip-10-0-1-175:~# docker logs $(docker ps -lq)
2015/04/03 21:39:01 routing all to rfc5424://logs-01.loggly.com:514?structured_data=<token>@41058
2015/04/03 21:39:01 loading and persisting routes in /mnt/routes
2015/04/03 21:39:01 logspout v2 serving http on :8000

root@ip-10-0-1-175:~# curl $(docker port `docker ps -lq` 8000)/logs
    serene_payne|[martini] Started GET /logs for 172.17.42.1:6891
mesos-fe4e98ca-57c0-4392-843a-10c7945ed07c|foo Fri Apr 3 21:39:09 UTC 2015
mesos-fe4e98ca-57c0-4392-843a-10c7945ed07c|foo Fri Apr 3 21:39:10 UTC 2015
mesos-fe4e98ca-57c0-4392-843a-10c7945ed07c|foo Fri Apr 3 21:39:11 UTC 2015
^C
```

##### structuredData
```console
root@ip-10-0-1-175:~# docker run -d -P -v=/var/run/docker.sock:/tmp/docker.sock gliderlabs/logspout:v2 "rfc5424://logs-01.loggly.com:514?structuredData=<token>@41058"
ca7fb69106dbe034ad21b437c317eea5da16b6b30dd704472d9cf4f0850bbbb9

root@ip-10-0-1-175:~# docker logs $(docker ps -lq)
2015/04/03 21:37:47 routing all to rfc5424://logs-01.loggly.com:514?structuredData=<token>@41058
2015/04/03 21:37:47 loading and persisting routes in /mnt/routes
2015/04/03 21:37:47 logspout v2 serving http on :8000

root@ip-10-0-1-175:~# curl $(docker port `docker ps -lq` 8000)/logs
condescending_torvalds|[martini] Started GET /logs for 172.17.42.1:59342
mesos-fe4e98ca-57c0-4392-843a-10c7945ed07c|foo Fri Apr 3 21:37:49 UTC 2015
mesos-fe4e98ca-57c0-4392-843a-10c7945ed07c|foo Fri Apr 3 21:37:50 UTC 2015
mesos-fe4e98ca-57c0-4392-843a-10c7945ed07c|foo Fri Apr 3 21:37:51 UTC 2015
^C
```

#### syslog+tcp
##### structured_data
```console
root@ip-10-0-1-175:~# docker run -d -P -v=/var/run/docker.sock:/tmp/docker.sock gliderlabs/logspout:v2 "syslog+tcp://logs-01.loggly.com:514?structured_data=<token>@41058"
e70222759e7dba17ebd4051b809510dc80d2d6708273d6ac04ffa5ee7f3f57c4

root@ip-10-0-1-175:~# docker logs $(docker ps -lq)
2015/04/03 21:35:06 routing all to syslog+tcp://logs-01.loggly.com:514?structured_data=<token>@41058
2015/04/03 21:35:06 loading and persisting routes in /mnt/routes
2015/04/03 21:35:06 logspout v2 serving http on :8000

root@ip-10-0-1-175:~# curl $(docker port `docker ps -lq` 8000)/logs
^C
```

##### structuredData
```console
root@ip-10-0-1-175:~# docker run -d -P -v=/var/run/docker.sock:/tmp/docker.sock gliderlabs/logspout:v2 "syslog+tcp://logs-01.loggly.com:514?structuredData=<token>@41058"
5af04e69bf4bdd942428e2c478661c76dbd0f835d909d189c52bb24509d503c5

root@ip-10-0-1-175:~# docker logs $(docker ps -lq)
2015/04/03 21:37:02 routing all to syslog+tcp://logs-01.loggly.com:514?structuredData=<token>@41058
2015/04/03 21:37:02 loading and persisting routes in /mnt/routes
2015/04/03 21:37:02 logspout v2 serving http on :8000

root@ip-10-0-1-175:~# curl $(docker port `docker ps -lq` 8000)/logs
^C
```

**Comment by progrium** [comment] 2015-04-03 22:41
Mmmm.. you want to be using master for syslog+tcp.

On Fri, Apr 3, 2015 at 4:47 PM, Mike Babineau <notifications@github.com>
wrote:

> I'm seeing the same issue with the v2 release. I kicked off a task to
> generate logs and tried each combination of structured_data/structuredData
> and rfc5424/syslog+tcp. Nothing ever showed up in Loggly.
>
> Note that for syslog+tcp, the HTTP endpoint did not return any of the
> generated logs, either.
> rfc5424 structured_data
>
> root@ip-10-0-1-175:~# docker run -d -P -v=/var/run/docker.sock:/tmp/docker.sock gliderlabs/logspout:v2 "rfc5424://logs-01.loggly.com:514?structured_data=<token>@41058"a3c3c3afa6701b8090425a474cf5572cc9bb2e68e91b8dcb54038ba74938baa0
> root@ip-10-0-1-175:~# docker logs $(docker ps -lq)2015/04/03 21:39:01 routing all to rfc5424://logs-01.loggly.com:514?structured_data=<token>@410582015/04/03 21:39:01 loading and persisting routes in /mnt/routes2015/04/03 21:39:01 logspout v2 serving http on :8000
> root@ip-10-0-1-175:~# curl $(docker port `docker ps -lq` 8000)/logs    serene_payne|[martini] Started GET /logs for 172.17.42.1:6891mesos-fe4e98ca-57c0-4392-843a-10c7945ed07c|foo Fri Apr 3 21:39:09 UTC 2015mesos-fe4e98ca-57c0-4392-843a-10c7945ed07c|foo Fri Apr 3 21:39:10 UTC 2015mesos-fe4e98ca-57c0-4392-843a-10c7945ed07c|foo Fri Apr 3 21:39:11 UTC 2015^C
>
> structuredData
>
> root@ip-10-0-1-175:~# docker run -d -P -v=/var/run/docker.sock:/tmp/docker.sock gliderlabs/logspout:v2 "rfc5424://logs-01.loggly.com:514?structuredData=<token>@41058"ca7fb69106dbe034ad21b437c317eea5da16b6b30dd704472d9cf4f0850bbbb9
> root@ip-10-0-1-175:~# docker logs $(docker ps -lq)2015/04/03 21:37:47 routing all to rfc5424://logs-01.loggly.com:514?structuredData=<token>@410582015/04/03 21:37:47 loading and persisting routes in /mnt/routes2015/04/03 21:37:47 logspout v2 serving http on :8000
> root@ip-10-0-1-175:~# curl $(docker port `docker ps -lq` 8000)/logscondescending_torvalds|[martini] Started GET /logs for 172.17.42.1:59342mesos-fe4e98ca-57c0-4392-843a-10c7945ed07c|foo Fri Apr 3 21:37:49 UTC 2015mesos-fe4e98ca-57c0-4392-843a-10c7945ed07c|foo Fri Apr 3 21:37:50 UTC 2015mesos-fe4e98ca-57c0-4392-843a-10c7945ed07c|foo Fri Apr 3 21:37:51 UTC 2015^C
>
> syslog+tcp structured_data
>
> root@ip-10-0-1-175:~# docker run -d -P -v=/var/run/docker.sock:/tmp/docker.sock gliderlabs/logspout:v2 "syslog+tcp://logs-01.loggly.com:514?structured_data=<token>@41058"e70222759e7dba17ebd4051b809510dc80d2d6708273d6ac04ffa5ee7f3f57c4
> root@ip-10-0-1-175:~# docker logs $(docker ps -lq)2015/04/03 21:35:06 routing all to syslog+tcp://logs-01.loggly.com:514?structured_data=<token>@410582015/04/03 21:35:06 loading and persisting routes in /mnt/routes2015/04/03 21:35:06 logspout v2 serving http on :8000
> root@ip-10-0-1-175:~# curl $(docker port `docker ps -lq` 8000)/logs^C
>
> structuredData
>
> root@ip-10-0-1-175:~# docker run -d -P -v=/var/run/docker.sock:/tmp/docker.sock gliderlabs/logspout:v2 "syslog+tcp://logs-01.loggly.com:514?structuredData=<token>@41058"5af04e69bf4bdd942428e2c478661c76dbd0f835d909d189c52bb24509d503c5
> root@ip-10-0-1-175:~# docker logs $(docker ps -lq)2015/04/03 21:37:02 routing all to syslog+tcp://logs-01.loggly.com:514?structuredData=<token>@410582015/04/03 21:37:02 loading and persisting routes in /mnt/routes2015/04/03 21:37:02 logspout v2 serving http on :8000
> root@ip-10-0-1-175:~# curl $(docker port `docker ps -lq` 8000)/logs^C
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gliderlabs/logspout/issues/25#issuecomment-89429681>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by thedug** [comment] 2015-04-16 20:43
Has anybody had any successfully sent tags to loggly using logspout

**Comment by thedug** [comment] 2015-04-17 00:13
This works: 
docker run --restart=always --name logspout -d -v=/var/run/docker.sock:/tmp/docker.sock progrium/logspout
"rfc5424://logs-01.loggly.com:514?structuredData=<token>@41058 tag=\"Docker\""

**Comment by alph486** [comment] 2015-12-23 19:28
Probably naive question, but where is the 'connect string' specification and options documented? Like where did @thedug get `tag=Docker` param and @harlow get the structuredData param?

**Comment by alph486** [comment] 2015-12-23 21:41
Tried doing what @thedug posted but doesnt seem to work with loggly at time of writing. Using :latest

**Comment by rsingh2411** [comment] 2016-01-21 12:56
Hi I am trying to send logs to a remote syslog server using logspout 
I am using url syslog+tcp://192.168.50.151:5555 but i don't see any logs in syslog server,
howver when changing to udp i see that logs are coming in syslog server

does syslog+tcp doesn't work.

I get following on console when
2016/01/21 12:55:52 routing all to syslog+tcp://192.168.50.151:5555
2016/01/21 12:55:52 loading and persisting routes in /mnt/routes
2016/01/21 12:55:52 logspout v2 serving http on :8000

**Comment by jodonovan** [comment] 2016-02-18 18:34
I'm seeing the same thing.
