### ISSUE TITLE
Ignore env variable for containers not working

### ISSUE THREAD

**Issue by jmstone617** [gliderlabs/logspout#102] opened 2015-05-25 21:32 UTC
I've started logspout with the following command:
`docker run -d --name logspout --volume=/var/run/docker.sock:/tmp/docker.sock -d -h hostname gliderlabs/logspout syslog://[REDACTED]`

And started another container with
`docker run -d --name ambassador --expose 1234 -e "LOGSPOUT=ignore" -e svendowideit/ambassador`

And I'm still seeing the logs from this container getting pumped into my central logging server. Does order matter wrt which order I start the containers in? I've tried both and am getting the same result, but thought I'd make sure.

Output from `docker version`:
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64

**Comment by NamespaceValentine** [comment] 2015-06-15 22:42
Getting the same issue:
Trying to run an aws ecs server using logspout, I am starting logspout with:
```
docker run -d --name=logspout --volume=/var/run/docker.sock:/tmp/docker.sock --restart always gliderlabs/logspout syslog://[REDACTED]
```

And my ecs-agent is using a config file that contains:
LOGSPOUT=ignore

I can verify that the docker inspect shows the environment variable set in the ecs-agent container.

docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): 4749651/1.6.0
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): 4749651/1.6.0
OS/Arch (server): linux/amd64

**Comment by ben** [comment] 2015-07-14 15:57
:hand: I'm getting this too. Trying not to fill up my papertrail account with the output from `top` when running an ambassador container.

**Comment by jmstone617** [comment] 2015-07-14 16:15
Try the `master` tag of the container. I've had mixed success with that. Also, you can filter data from Papertrail so it's not destroying your stream (or data limits).

Just go to Account --> Log Destinations --> Edit Settings and enter a regex in the "Filter logs to this destination?" field. I have this (in addition to some other things): `\w*ambassador\w*`

**Comment by ben** [comment] 2015-07-14 17:29
Tried using `progrium/logspout:master`; the `LOGSPOUT=ignore` environment variable still isn't having any effect. Logs are still being shipped to papertrail.

I'll filter it at the papertrail level, thanks for the tip.

**Comment by BenHall** [comment] 2015-10-14 17:40
I had similar issues. Reason is because the :latest tag doesn't reflect the documentation and contain the IGNORE flag. 

You need to use the :master tagged image instead

**Comment by BDQ** [comment] 2015-10-23 10:08
I can confirm as @BenHall has said, this issue is resolved with :master tag.

**Comment by cricket007** [comment] 2016-01-14 16:13
+1 for :master tag

That should really be mentioned in the README

**Closed** 2016-05-04 22:26 UTC
Labels: type: documentation
