### ISSUE TITLE
Log pump closes after single send timeout

### ISSUE THREAD

**Issue by drewrobb** [gliderlabs/logspout#210] opened 2016-07-13 21:33 UTC
In prod we have noticed a single send timeout causes logs to stop being sent. In logspout logs we see messages like `2016/07/12 07:44:54 pump.send(): send timeout, closing` and then no more logs from that container are sent. 

The relevant code is here: https://github.com/markine/logspout/blob/324db6e01dda3aa6727c03cb3f29217728bd861f/router/pump.go#L332

Is it intended for the logstream to be restarted by some other mechanism? Looking to where this change was introduced, there was previously no `delete` here and a `// TODO: log err after timeout and continue`-- https://github.com/markine/logspout/commit/1d54f5e984f30bb38b7a9754333c15e80fd780da#diff-1e402098f7c31429ceb791bb7bbb6620L216

It seems to me that the behavior of deleting a logstream from a pump after a single send timeout is unreasonable if there is no other mechanism to restart it?

**Comment by josegonzalez** [comment] 2016-07-13 21:46
What version of logspout are you running?

**Comment by drewrobb** [comment] 2016-07-13 21:54
Logspout master branch. We are also using a fork of  https://github.com/rtoma/logspout-redis-logstash as an adaptor, and that is the source of timeouts. It appears that this commit: https://github.com/rtoma/logspout-redis-logstash/commit/b96fbb63fa275395647ce01601f80d645227e591#diff-bbc64daf788a83d9a6daf7056d49d2a8R115 actually addresses this issue by adding timeouts to satisfy the 1 second timeout in logspout. However we do not have not have this commit included in the version of logspout-redis-logstash we are running. Having this commit in our production version would probably fix our issue, however I think the underlying behavior of logspout is not good.

**Comment by ebr** [comment] 2016-08-23 14:39
We are seeing similar/same behaviour, suspecting this started after upgrading docker to v1.12. I also suspect #204 is a contributing factor.

**Comment by ebr** [comment] 2016-09-01 15:51
@drewrobb are you still sure the send timeout is the cause of this? I've narrowed it down to log rotation; we do get send timeouts, but i can't directly correlate them with this.

**Comment by drewrobb** [comment] 2016-09-01 16:12
@ebr we do not have docker log rotation setup and still (had previously) send timeouts. We updated to the latest logspout-redis-logstash and the comment I mentioned in the issue description didn't solve our problem. We are running this branch now: https://github.com/gliderlabs/logspout/compare/master...strava:dr/no-delete-logstream which finally fixed it for us. We are also on docker 1.12.

**Comment by dareid** [comment] 2016-09-14 06:56
I think we are seeing similar behaviour to this, any news on a fix being merged?

**Closed** 2016-09-23 20:14 UTC

**Comment by josegonzalez** [comment] 2016-09-23 20:16
A pull request was never made, so I just made it and waiting for tests to pass.

**Comment by drewrobb** [comment] 2016-09-23 20:27
@josegonzalez thanks! I'd be happy to see this in logspout, I didn't make a PR simply because I don't really know enough about logspout to know whether this change would be a bad thing in other scenarios. It has worked great for us in production with logspout-redis-logstash.

**Comment by fjollberg** [comment] 2016-11-14 12:18
I'm using logspout to forward messages to Azure OMS. I can confirm that I hit this timeout quite frequently causing log forwarding to stop. I figure this pull request would solve that issue.

**Comment by chrishiestand** [comment] 2016-11-14 19:16
@fjollberg you can pull this pull request and build it yourself to test that. I tried this PR to fix a similar (if not same) problem and it did not fix my issue.

**Comment by fjollberg** [comment] 2016-11-15 10:58
As I said, I'm already running essentially the same fix, however by increasing the timeout, but the effect is the same, the stream is not closed. In combination with the latest commit to logspout for the log rotation, so far my logs are up and running.

**Comment by daniilyar** [comment] 2017-01-16 21:56
Increasing the timeout in line https://github.com/gliderlabs/logspout/blob/master/router/pump.go#L346 (same as @fjollberg did) helped us also. We send logs to Logstash in Kubernetes using [our custom logstash-logspout plugin fork]() (which supports joining multiline logs and retries with backoff if Logstash is unavailable)
